
version: '2'
services:
  ###### initialization and dynamic configuration build services ###########
  init:
    build: dockerfiles/init
    command: ash -c "chown -R mijin:mijin /peer-node-0-data /peer-node-1-data /api-node-0-data /addresses /nemesis"
    volumes:
    - ./bin/ash:/bin-mount
    - ./data/peer-node-0:/peer-node-0-data:rw
    - ./data/peer-node-1:/peer-node-1-data:rw
    - ./data/api-node-0:/api-node-0-data:rw
    - nemesis/:/nemesis:rw
    - addresses:/addresses:rw

  generate-raw-addresses:
    build: dockerfiles/catapult
    command: /bin-mount/generate-raw-addresses-if-needed 50 /addresses/raw-addresses.txt /catapult-addresses/addresses.yaml
    environment:
    - LOCAL_USER_ID=1000
    volumes:
    - ./bin/bash:/bin-mount
    - addresses:/addresses:rw
    - ./generated-catapult-addresses:/catapult-addresses:rw

  store-addresses:
    build: dockerfiles/ruby-alpine
    command: ash -c "/bin-mount/wait /addresses/raw-addresses.txt && /ruby/bin/store-addresses-if-needed.rb /addresses/raw-addresses.txt /catapult-addresses/addresses.yaml" 
    volumes:
    - ./bin/ash:/bin-mount
    - ./ruby:/ruby
    - ./generated-catapult-addresses:/catapult-addresses:rw
    - addresses:/addresses

  generate-configs:
    build: dockerfiles/ruby-alpine
    command: ash -c "/bin-mount/wait /addresses/addresses.yaml && /ruby/bin/generate-and-write-configurations.rb /addresses/addresses.yaml /config-build /nemesis"
    volumes:
    - ./bin/ash:/bin-mount
    - ./ruby:/ruby
    - ./generated-catapult-addresses:/addresses
    - ./catapult-config-build:/config-build
    - nemesis:/nemesis:rw

  ###### running services ###########

  db:
    image: mongo
    command: bash -c "mongod --dbpath=/dbdata --bind_ip=db"
    stop_signal: SIGINT
    volumes:
    - ./data/mongo:/dbdata:rw
    - ./bin/bash:/bin-mount

  init-db:
    image: mongo
    command:  bash -c "/bin/bash /userconfig/mongors.sh"
    volumes:
    - ./data/mongo:/dbdata:rw
    - ./catapult-config/mongo/:/userconfig/:ro
    - ./bin/bash:/bin-mount
    depends_on:
    - db

  rest-gateway:
    build: dockerfiles/rest-gateway
    command: ash /userconfig/rest.sh
    ports:
    - "3000:3000"
    volumes:
    - ./catapult-config-build/rest-gateway-0/userconfig/:/userconfig/
    depends_on:
    - init-db
    - generate-configs

  peer-node-0:
    build: dockerfiles/catapult
    environment:
    - LOCAL_USER_ID=1000
    command: bash -c "/bin/bash /userconfig/startServer.sh"
    stop_signal: SIGINT
    volumes:
    - ./catapult-config-build/peer-node-0/userconfig/resources/:/userconfig/resources/
    - nemesis/:/nemesis:rw
    - ./data/peer-node-0:/data:rw
    depends_on:
    - init
    - generate-configs

  peer-node-1:
    build: dockerfiles/catapult
    environment:
    - LOCAL_USER_ID=1000
    command: bash -c "/bin/bash /userconfig/startServer.sh"
    stop_signal: SIGINT
    volumes:
    - ./catapult-config-build/peer-node-1/userconfig/resources/:/userconfig/resources/
    - nemesis/:/nemesis:rw
    - ./data/peer-node-1:/data:rw
    depends_on:
    - init
    - generate-configs

  api-node-0:
    build: dockerfiles/catapult
    environment:
    - LOCAL_USER_ID=1000
    command: bash -c "/bin/bash /userconfig/startServer.sh"
    stop_signal: SIGINT
    volumes:
    - ./catapult-config-build/api-node-0/userconfig/resources/:/userconfig/resources/
    - nemesis/:/nemesis:rw
    - ./data/api-node-0:/data:rw
    depends_on:
    - init
    - generate-configs
    - init-db

volumes:
  addresses:
  nemesis: