version: '2'
services:
  init:
    image: alpine
    volumes:
    - order-sync:/order-sync
    - ./data/mongo:/dbdata:rw
    command: ash -c "chmod 666 /order-sync && touch /order-sync/init"

  db:
    image: mongo
    command: bash -c "/bin-mount/wait /order-sync/initiate-db && mongod --dbpath=/dbdata --bind_ip=db"
    stop_signal: SIGINT
    volumes:
    - ./data/mongo:/dbdata:rw
    - ./bin/bash:/bin-mount
    - order-sync:/order-sync
    depends_on:
    - init

  init-db:
    image: mongo
    command:  bash -c "/bin/bash /userconfig/mongors.sh && touch /order-sync/init-db"
    volumes:
    - ./catapult-config/static/mongo/:/userconfig/:ro
    - ./bin/bash:/bin-mount
    - order-sync:/order-sync
    depends_on:
    - db

  rest-gateway:
    image: jenkins.nem.ninja:8443/catapult-rest:master
    command: ash -c "/bin-mount/wait /order-sync/init-db && /bin/ash /userconfig/rest.sh"
    ports:
    - "3000:3000"
    volumes:
    - ./catapult-config/static/rest-gateway/:/userconfig/
    - ./bin/ash:/bin-mount
    - order-sync:/order-sync
    depends_on:
    - init-db

volumes:
  order-sync: