version: '2'
services:
  ###### initialization and dynamic configuration build services ###########
  init:
    build: dockerfiles/init
    command: ash -c "chown -R mijin:mijin /peer-node-0-data /peer-node-1-data /api-node-0-data /addresses /nemesis /state && touch /state/init"
    volumes:
    - ./bin/ash:/bin-mount
    - ./data/peer-node-0:/peer-node-0-data:rw
    - ./data/peer-node-1:/peer-node-1-data:rw
    - ./data/api-node-0:/api-node-0-data:rw
    - ./build/nemesis/:/nemesis:rw
    - ./build/generated-addresses:/addresses:rw
    - ./build/state:/state:rw

  generate-raw-addresses:
    image: jenkins.nem.ninja:8443/catapult-slim-server-v2:master_release-gcc
    command: bash -c "/bin-mount/wait /state/init && /bin-mount/generate-raw-addresses-if-needed 50 /addresses/raw-addresses.txt /addresses/addresses.yaml"
    environment:
    - LOCAL_USER_ID=1000
    volumes:
    - ./bin/bash:/bin-mount
    - ./build/generated-addresses:/addresses:rw
    - ./build/state:/state:rw

  store-addresses:
    build: dockerfiles/ruby-alpine
    command: ash -c "/bin-mount/wait /addresses/raw-addresses.txt && /ruby/bin/store-addresses-if-needed.rb /addresses/raw-addresses.txt /addresses/addresses.yaml"
    volumes:
    - ./bin/ash:/bin-mount
    - ./ruby:/ruby
    - ./build/generated-addresses:/addresses:rw

  generate-configs:
    build: dockerfiles/ruby-alpine
    command: ash -c "/bin-mount/wait /addresses/addresses.yaml && /ruby/bin/generate-and-write-configurations.rb /addresses/addresses.yaml /config-build /nemesis && touch /state/configs-generated"
    volumes:
    - ./bin/ash:/bin-mount
    - ./ruby:/ruby
    - ./build/generated-addresses:/addresses
    - ./build/catapult-config:/config-build
    - ./build/nemesis:/nemesis:rw
    - ./build/state:/state:rw

  ###### running services ###########

  db:
    image: mongo
    command: bash -c "mongod --dbpath=/dbdata --bind_ip=db"
    stop_signal: SIGINT
    volumes:
    - ./data/mongo:/dbdata:rw
    - ./bin/bash:/bin-mount

  init-db:
    image: mongo
    command:  bash -c "/bin/bash /userconfig/mongors.sh"
    volumes:
    - ./data/mongo:/dbdata:rw
    - ./static-config/mongo/:/userconfig/:ro
    - ./bin/bash:/bin-mount
    depends_on:
    - db

  rest-gateway:
    image: jenkins.nem.ninja:8443/catapult-rest:master
    command: ash -c "/bin-mount/wait /state/configs-generated && npm start resources/rest.json /userconfig/rest.json"
    ports:
    - "3000:3000"
    volumes:
    - ./build/catapult-config/rest-gateway-0/userconfig/:/userconfig/
    - ./bin/ash:/bin-mount
    - ./build/state:/state
    depends_on:
    - init-db
    - generate-configs

  peer-node-0-nemgen:
    build: dockerfiles/nemgen
    environment:
    - LOCAL_USER_ID=1000
    command: bash -c "/bin-mount/wait /state/configs-generated && /bin/bash /userconfig/nemgen.sh && touch /state/peer-node-0-nemgen"
    stop_signal: SIGINT
    volumes:
    - ./build/nemesis/:/nemesis
    - ./data/peer-node-0:/data:rw
    - ./bin/bash:/bin-mount
    - ./build/state:/state:rw
    depends_on:
    - init
    - generate-configs

  peer-node-0:
    build: dockerfiles/catapult
    environment:
    - LOCAL_USER_ID=1000
    command: bash -c "/bin-mount/wait /state/peer-node-0-nemgen && /bin/bash /userconfig/startServer.sh"
    stop_signal: SIGINT
    volumes:
    - ./build/catapult-config/peer-node-0/userconfig/resources/:/userconfig/resources/
    - ./data/peer-node-0:/data:rw
    - ./bin/bash:/bin-mount
    - ./build/state:/state
    depends_on:
    - init
    - generate-configs
    - peer-node-0-nemgen

  peer-node-1-nemgen:
    build: dockerfiles/nemgen
    environment:
    - LOCAL_USER_ID=1000
    command: bash -c "/bin-mount/wait /state/configs-generated && /bin/bash /userconfig/nemgen.sh && touch /state/peer-node-1-nemgen"
    stop_signal: SIGINT
    volumes:
    - ./build/nemesis/:/nemesis
    - ./data/peer-node-1:/data:rw
    - ./bin/bash:/bin-mount
    - ./build/state:/state:rw
    depends_on:
    - init
    - generate-configs

  peer-node-1:
    build: dockerfiles/catapult
    environment:
    - LOCAL_USER_ID=1000
    command: bash -c "/bin-mount/wait /state/peer-node-1-nemgen && /bin/bash /userconfig/startServer.sh"
    stop_signal: SIGINT
    volumes:
    - ./build/catapult-config/peer-node-1/userconfig/resources/:/userconfig/resources/
    - ./data/peer-node-1:/data:rw
    - ./bin/bash:/bin-mount
    - ./build/state:/state
    depends_on:
    - init
    - generate-configs
    - peer-node-1-nemgen


  api-node-0-nemgen:
    build: dockerfiles/nemgen
    environment:
    - LOCAL_USER_ID=1000
    command: bash -c "/bin-mount/wait /state/configs-generated && /bin/bash /userconfig/nemgen.sh && touch /state/api-node-0-nemgen"
    stop_signal: SIGINT
    volumes:
    - ./build/nemesis/:/nemesis
    - ./data/api-node-0:/data:rw
    - ./bin/bash:/bin-mount
    - ./build/state:/state:rw
    depends_on:
    - init
    - generate-configs

  api-node-0:
    build: dockerfiles/catapult
    environment:
    - LOCAL_USER_ID=1000
    command: bash -c "/bin-mount/wait /state/api-node-0-nemgen && /bin/bash /userconfig/startServer.sh"
    stop_signal: SIGINT
    volumes:
    - ./build/catapult-config/api-node-0/userconfig/resources/:/userconfig/resources/
    - ./data/api-node-0:/data:rw
    - ./bin/bash:/bin-mount
    - ./build/state:/state
    depends_on:
    - init
    - generate-configs
    - api-node-0-nemgen

