version: '2'
services:
  init:
    build: dockerfiles/init
    command: ash -c "chown -R mijin:mijin /peer-node-0-data /peer-node-1-data /api-node-0-data /addresses"
    volumes:
    - ./bin/ash:/bin-mount
    - ./data/peer-node-0:/peer-node-0-data:rw
    - ./data/peer-node-1:/peer-node-1-data:rw
    - ./data/api-node-0:/api-node-0-data:rw
    - addresses:/addresses:rw
  db:
    image: mongo
    command: bash -c "/bin-mount/wait /order-sync/initiate-db && mongod --dbpath=/dbdata --bind_ip=db"
    stop_signal: SIGINT
    volumes:
    - ./data/mongo:/dbdata:rw
    - ./bin/bash:/bin-mount
    - order-sync:/order-sync:rw

  init-db:
    image: mongo
    command:  bash -c "/bin/bash /userconfig/mongors.sh && touch /order-sync/init-db"
    volumes:
    - ./catapult-config/mongo/:/userconfig/:ro
    - ./bin/bash:/bin-mount
    - order-sync:/order-sync:rw
    depends_on:
    - db
  rest-gateway:
    image: jenkins.nem.ninja:8443/catapult-rest:master
    command: ash -c "/bin-mount/wait /order-sync/init-db && /bin/ash /userconfig/rest.sh"
    ports:
    - "3000:3000"
    volumes:
    - ./catapult-config/rest-gateway/:/userconfig/
    - ./bin/ash:/bin-mount
    - order-sync:/order-sync
    depends_on:
    - init-db

##### catapult nodes

  generate-raw-addresses:
    image: jenkins.nem.ninja:8443/catapult-slim-server:master_release-gcc
    command: /bin-mount/generate-raw-addresses-if-needed 50 /addresses/raw-addresses.txt /catapult-addresses/addresses.yaml
    environment:
    - LOCAL_USER_ID=1000
    volumes:
    - ./bin/bash:/bin-mount
    - addresses:/addresses:rw
    - ./generated-catapult-addresses:/catapult-addresses:rw

  store-addresses:
    build: dockerfiles/ruby-alpine
    command: ash -c "/bin-mount/wait /addresses/raw-addresses.txt && /ruby/bin/store-addresses-if-needed.rb /addresses/raw-addresses.txt /catapult-addresses/addresses.yaml" 
    volumes:
    - ./bin/ash:/bin-mount
    - ./ruby:/ruby
    - ./generated-catapult-addresses:/catapult-addresses:rw
    - addresses:/addresses

  generate-configs:
    build: dockerfiles/ruby-alpine
    command: ash -c "/bin-mount/wait /addresses/addresses.yaml && /ruby/bin/generate-and-write-configurations.rb /addresses/addresses.yaml /config-build /nemesis && touch /order-sync/generate-configs"
    volumes:
    - ./bin/ash:/bin-mount
    - ./ruby:/ruby
    - ./generated-catapult-addresses:/addresses
    - ./catapult-config-build:/config-build
    - nemesis:/nemesis:rw
    - order-sync:/order-sync:rw

  peer-node-0:
    image: jenkins.nem.ninja:8443/catapult-slim-server:master_release-gcc
    environment:
    - LOCAL_USER_ID=1000
    logging:
      driver: "json-file"
      options:
        max-size: "25M"
        max-file: "10"
    command: bash -c "/bin/bash /userconfig/startServer.sh"
    stop_signal: SIGINT
    volumes:
    - ./catapult-config/catpult-node/:/userconfig/
    - ./catapult-config-build/peer-node-0/userconfig/resources/:/userconfig/resources/
    -  nemesis/:/nemesis/
    - ./data/peer-node-0:/data:rw
    depends_on:
    - init
    - generate-configs

  peer-node-1:
    image: jenkins.nem.ninja:8443/catapult-slim-server:master_release-gcc
    environment:
    - LOCAL_USER_ID=1000
    logging:
      driver: "json-file"
      options:
        max-size: "25M"
        max-file: "10"
    command: bash -c "/bin/bash /userconfig/startServer.sh"
    stop_signal: SIGINT
    volumes:
    - ./catapult-config/catpult-node/:/userconfig/
    - ./catapult-config-build/peer-node-1/userconfig/resources/:/userconfig/resources/
    -  nemesis/:/nemesis/
    - ./data/peer-node-1:/data:rw
    depends_on:
    - init
    - generate-configs

  api-node-0:
    image: jenkins.nem.ninja:8443/catapult-slim-server:master_release-gcc
    environment:
    - LOCAL_USER_ID=1000
    logging:
      driver: "json-file"
      options:
        max-size: "25M"
        max-file: "10"
    command: bash -c "/bin/bash /userconfig/startServer.sh"
    stop_signal: SIGINT
    volumes:
    - ./catapult-config/catpult-node/:/userconfig/
    - ./catapult-config-build/api-node-0/userconfig/resources/:/userconfig/resources/
    -  nemesis/:/nemesis/
    - ./data/api-node-0:/data:rw
    depends_on:
    - init
    - generate-configs

volumes:
  order-sync:
  addresses:
  nemesis: