version: '2'
services:
  init:
    image: alpine
    volumes:
    - order-sync:/order-sync:rw
    - ./data/mongo:/dbdata:rw
    command: touch /order-sync/init

  generate-raw-addresses:
    image: jenkins.nem.ninja:8443/catapult-slim-server:master_release-gcc
    command: /bin-mount/generate-raw-addresses-if-needed 50 /addresses/raw-addresses.txt /catapult-addresses/addresses.yaml
    volumes:
    - ./bin/bash:/bin-mount
    - addresses:/addresses:rw
    - ./generated-catapult-addresses:/catapult-addresses:rw
  store-addreses:
    build: ruby-alpine
    command: ash -c "/bin-mount/wait /addresses/raw-addresses.txt && /ruby/bin/store-addresses-if-needed.rb /addresses/raw-addresses.txt /catapult-addresses/addresses.yaml" 
    volumes:
    - ./bin/ash:/bin-mount
    - ./ruby:/ruby
    - ./generated-catapult-addresses:/catapult-addresses:rw
    - addresses:/addresses

  db:
    image: mongo
    command: bash -c "/bin-mount/wait /order-sync/initiate-db && mongod --dbpath=/dbdata --bind_ip=db"
    stop_signal: SIGINT
    volumes:
    - ./data/mongo:/dbdata:rw
    - ./bin/bash:/bin-mount
    - order-sync:/order-sync:rw
    depends_on:
    - init

  init-db:
    image: mongo
    command:  bash -c "/bin/bash /userconfig/mongors.sh && touch /order-sync/init-db"
    volumes:
    - ./catapult-config/static/mongo/:/userconfig/:ro
    - ./bin/bash:/bin-mount
    - order-sync:/order-sync:rw
    depends_on:
    - db
  peer-node-0:
    image: jenkins.nem.ninja:8443/catapult-slim-server:master_release-gcc
#    environment:
#      - LOCAL_USER_ID=1000
    logging:
      driver: "json-file"
      options:
        max-size: "25M"
        max-file: "10"
#    command: bash -c "/bin/bash /userconfig/startServer.sh
    command: bash -c "sleep 10000"
    stop_signal: SIGINT
    volumes:
    - ./catapult-config/static/catpult-node/:/userconfig/
    - ./catapult-config-build/peer-node-0/userconfig/resources/:/userconfig/resources/
    - ./nemesis/:/nemesis/
    - ./data/peer-node-0:/data:rw
  rest-gateway:
    image: jenkins.nem.ninja:8443/catapult-rest:master
    command: ash -c "/bin-mount/wait /order-sync/init-db && /bin/ash /userconfig/rest.sh"
    ports:
    - "3000:3000"
    volumes:
    - ./catapult-config/static/rest-gateway/:/userconfig/
    - ./bin/ash:/bin-mount
    - order-sync:/order-sync
    depends_on:
    - init-db

volumes:
  order-sync:
  addresses: