version: '2'
services:

  init-order-sync:
   image: alpine
   volumes:
    - order-sync:/order-sync
   command: ash -c "chmod 777 /order-sync && touch /order-sync/initialized"

  initiate-db:
    image: mongo
    command:  bash -c "/order-sync/bash/wait /order-sync/init-order-sync && /bin/bash /userconfig/mongors.sh && touch /order-sync/initiate-db"
    command: /bin/bash /userconfig/mongors.sh
    volumes:
      - ./config-store/mongo:/userconfig:ro
    depends_on:
      - init-order-sync

  db:
    image: mongo
    user: "1000:1000"
    command: mongod --dbpath=/dbdata
    stop_signal: SIGINT
    volumes:
    - order-sync:/order-sync
    - ./data/db:/dbdata:rw
    ports:
    - "27017:27017"

  rest:
    image: jenkins.nem.ninja:8443/catapult-rest:master
    command: /bin/ash  /userconfig/rest.sh
    ports:
      - "3000:3000"
#      - "9229:9229"
    volumes:
      - ./rest-gateway:/userconfig
    depends_on:
      - initiate

#### for peer and api nodes
  pre:
   image: alpine
   volumes:
    - order-sync:/order-sync
   command: ash -c "chmod 777 /order-sync && touch /order-sync/1"
  generate-addresses:
    image: jenkins.nem.ninja:8443/catapult-slim-server:master_release-gcc
    command:  bash -c "/bin-mount/wait /order-sync/1 && /catapult/bin/catapult.tools.address --generate=50 > /order-sync/raw-addresses.txt && touch /order-sync/2"
    volumes:
    - order-sync:/order-sync
    - ./bin/bash:/bin-mount
  ruby-alpine:
    build: ruby-alpine
    command: ash -c "/bin-mount/wait /order-sync/2 && ruby /bin/ruby/format.rb /order-sync/raw-addresses.txt"
#    command: sleep 10000
    volumes:
    - order-sync:/order-sync
    - ./bin/ash:/bin-mount
    - ./bin/ruby:/bin/ruby

volumes:
  order-sync: